server:
  port: 8080

spring:
  application:
    name: LibraryManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/lms
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl:
        auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

logging:
  level:
    org.springframework.security: TRACE

api:
  endpoint:
    base-url: /api/v1
